### ISSUE TITLE
GPLv2 vs Apache License Issue

### ISSUE THREAD

**Issue by bernhardttom** [pulsarIO/realtime-analytics#1]
Since GPLv2 is not compatible with Apache 2.0 it is not possible to grant both licenses.
You would need to change to GPLv2 for the entire project.

**Comment by shmurthy62** [comment]
We have 3 repos - one is core called Jetstream which can be used by itself. It is licensed under dual license (MIT + Apache). However jetstream-esper and realtime analytics are under GPLV2 and when Jetstream is used with either of these it automatically comes under GPLv2. Are you saying even that is not acceptable?Date: Mon, 23 Feb 2015 14:29:48 -0800

**Comment by bernhardttom** [comment]
The license for "jetstream-esper" must be GPLv2 only and an Apache license cannot also be granted.

For this project this should be the same since "jetstream-esper" must be GPLv2 licensed.

Apache v2 and GPLv2 are not compatible.

http://www.gnu.org/licenses/gpl-faq.html#WhatIsCompatible
http://en.wikipedia.org/wiki/Apache_License#GPL_compatibility

**Comment by mdyuan** [comment]
Hi Tom, thanks for your comment.  Our understanding is there's no requirement that two licenses in a dual licensing scheme be compatible with each other.  In the accepted tri-licensing scheme MPL 1.1-GPL v2-LGPL v2.1 (used in early versions of Firefox, for example), MPL 1.1 and GPL v2 were incompatible with each other.  

The dual license covers the project code only, and not third party code. We've made the code dual-licensed to give users the option to take the code under GPLv2 if they want to integrate with Esper or under Apache 2.0 if they want to use an alternative to Esper (which we recognize would require some additional revision to the code).  If a user took the project code under Apache and integrated with Esper, there would be a license incompatibility, in which case, the user should have taken the project code under GPL v2.

**Comment by bernhardttom** [comment]
Under the following link: http://www.gnu.org/licenses/gpl-faq.html#WhatIsCompatible

You can find this:
In order to combine two programs (or substantial parts of them) into a larger work, you need to have permission to use both programs in this way. If the two programs' licenses permit this, they are compatible. If there is no way to satisfy both licenses at once, they are incompatible.

In "jetstream-esper" you are combining two programs into a larger work however the two program's licenses are not compatible.

**Comment by mdyuan** [comment]
Right, I agree with what you're citing.  There is a way for both licenses to be satisfied - you take the jetstream-esper code under the GPL v2 option in the dual-licensing scheme.  If you don't combine jetstream-esper with Esper, then GPL doesn't come into play.

**Comment by bernhardttom** [comment]
Because "jetstream-esper" uses Esper under GPLv2 it's code automatically must be GPLv2 licensed and cannot also be Apache v2 licensed. It is a constraint expressed by the copyright holder of Esper that you can use Esper under GPLv2 license only (and not Apache). It is a requirements of GPLv2 that the derived code is also GPLv2 (and not Apache).

If an end user wanted to take "jetstream-esper" under Apache v2 license that end user would have to remove all references of Esper in your "jetstream-esper" code which would be impossible.

See http://www.apache.org/licenses/GPL-compatibility.html
See http://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html

**Comment by bernhardttom** [comment]
There is no clear statement anywhere on your web sites what license applies, especially on "http://gopulsar.io".
The various Github projects have "LICENSE" files and other then that there is no information.

Please read: http://wiki.egee-see.org/index.php/Licensing_and_FOSS_Guidelines
Read "while Apache 2.0 licensed products cannot use (L)GPL components."

This is EBay right? You would think Ebay can get license use right.

**Comment by mdyuan** [comment]
Tom - there's a misunderstanding on our end of what's in the code.  We will make the switch to GPLv2 only for "jetstream-esper" and "real-time analytics" ASAP.  Our apologies, and please bear with us as we make the license switch.  Will this satisfy your concerns?

**Comment by bernhardttom** [comment]
Sure yup. I'd suggest adding some license information to the site at http://gopulsar.io

**Comment by mdyuan** [comment]
I will strongly recommend to our folks that they do that.  Thanks again for bringing this to our attention.

**Comment by shmurthy62** [comment]
jetstream-esper has updated license info as of now. We will upgrade real-time-analytics soon. Please bear with us till then.
Date: Mon, 23 Feb 2015 16:52:49 -0800

**Comment by shmurthy62** [comment]
Issue is resolved - moved to GPLv2 license.
