### ISSUE TITLE
Exception while building project

### ISSUE THREAD

**Issue by ankit1987** [pulsarIO/realtime-analytics#11]
Hi,
I am getting following error while building this project.

[ERROR] Failed to execute goal on project collector: Could not resolve dependencies for project com.ebay.pulsar:collector:jar:1.0.0: Could not transfer artifact com.ebay.jetstream:jetstream-esper:jar:4.0.2 from/to snapshots (http://server.development.com:8080/libs-snapshot): Failed to transfer file: http://server.development.com:8080/libs-snapshot/com/ebay/jetstream/jetstream-esper/4.0.2/jetstream-esper-4.0.2.jar. Return code is: 409

**Comment by xinglang** [comment]
Hi,

The com.ebay.jetstream:jetstream-esper:jar:4.0.2  have been uploaded to maven central repo. Could you please check you maven setting or mirror setting?

Thanks,
Xinglang

**Comment by xinglang** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cjetstream-esper

**Comment by xinglang** [comment]
Closed as this is not an issue.
