### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [pulsarIO/realtime-analytics#15]
Can you more to ASL 2.0 which is more business friendly?

**Comment by shmurthy62** [comment]
The realtime analytics project can not move to ASL 2.0 as we use Esper which has a GPL license. However the Jetstream project is open sourced as ASL 2.0. If you build applications without Esper then it will be ASL 2.0

**Comment by bernhardttom** [comment]
Please add the GPLv2 license to the Jetstream top project, because if you build applications with Esper or with realtime-analytics (GPLv2) or with jetstream-esper (GPLv2) then that is GPLv2 license. It is not valid to grant ASL2.0 with an "if", see https://dzone.com/articles/who-owns-your-packages
