### ISSUE TITLE
Document missing -  https://github.com/pulsarIO/realtime-analytics/Get-Started

### ISSUE THREAD

**Issue by tovenka9** [pulsarIO/realtime-analytics#17]
Please provide this document  https://github.com/pulsarIO/realtime-analytics/Get-Started  for setting the Real time analytics demo apps

**Comment by xinglang** [comment]
https://github.com/pulsarIO/realtime-analytics/wiki/Get-Started

We will fix the broken link, could you please let me know which page has the broken link? Thanks!

Best regards,
Xinglang

**Comment by tovenka9** [comment]
Hi Xinglang Wang,

With this Web page

https://github.com/pulsarIO/realtime-analytics/wiki/PulsarIO-Demo  --
 Pre-Request  for setup the pipeline

Best Regards,
A.Venkatram.

**Comment by fiwang** [comment]
Thanks a lot for catching the problem. We’ve already fixed the problem.

Thanks,
Fiona

**Comment by tovenka9** [comment]
Hi,

Page not found is the response for this URL:
https://github.com/pulsarIO/realtime-analytics/Get-Started

Please Check once again.

Regards,
A.Venkatram.

**Comment by fiwang** [comment]
https://github.com/pulsarIO/realtime-analytics/wiki/Get-Started

Please try the above one.

Could you share me where you get the below link?

Thanks,
Fiona
