### ISSUE TITLE
demo project - parent pom

### ISSUE THREAD

**Issue by mariusrugan** [pulsarIO/realtime-analytics#5]
Hi,

What would be your thoughts in moving/ Demo app's 1 level up in the project? They pretty much are good candidates for it.
Right now development setup requires 2 IDE instances and it's a bit annoying to debug flows. 

I've setup a wiki page to outline setup with IDEA at:
https://github.com/pulsarIO/realtime-analytics/wiki/Run-Demo-&-local-development-setup-with-IntelliJ-IDEA

**Comment by xinglang** [comment]
the document is pretty good.

The reason why we separate it:

The demo is just for demo purpose, and the first level projects are the real-time analytics pipeline people can reuse it directly. 

How about I add Demo/pom.xml to parent pom and keep the hierarchy, will it be helpful on IDEA?

**Comment by mariusrugan** [comment]
Hi,

that sounds good, i forked to do that also :)

however, Simulator in collector project could be part of the demo folder
too, right?
