### ISSUE TITLE
Merge wiki changes

### ISSUE THREAD

**Issue by mariusrugan** [pulsarIO/realtime-analytics#6]
Hi,
i've modified the setup page for IDEA following changes in pom dependencies & added few more changes/upgrades

repo is at : https://github.com/MariusRugan/realtime-analytics.wiki.git
modifications are for: Run-Demo-&-local-development-setup-with-IntelliJ-IDEA.md

PS: guide for merging wiki is: https://gist.github.com/larrybotha/10650410

**Comment by xinglang** [comment]
Hi Marius - I am not able to pull your wiki git repo. Can you make it public?

**Comment by xinglang** [comment]
Hi Marius - You should be able to update the wiki directly now, can you try it?

**Comment by mariusrugan** [comment]
Hi Xinglang,

that's strange, wikis for public repos are public. (as i don't see any setting to make it more public)
I've tested without logging in, https://github.com/MariusRugan/realtime-analytics/wiki (and subsequent, wiki repo is at https://github.com/MariusRugan/realtime-analytics/wiki.git)

I see that you've reverted the restriction for wiki, thanks, will add directly here. (I am able to edit the page)
